title: LCD 151
description: Computational Linguistics
theme: just-the-docs

url: "https://lihan829.github.io"
baseurl: "/151F26/"

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"

# Enable or disable heading anchors
heading_anchors: true

# Don't let Jekyll try to process the Slidev source projects
exclude:
  - lectures/Lecture2/source

